<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SchoolCampusesTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('school_campuses')->delete();
        
        \DB::table('school_campuses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 1,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:15:37',
                'updated_at' => '2024-10-07 11:15:37',
            ),
            1 => 
            array (
                'id' => 2,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            2 => 
            array (
                'id' => 3,
                'campus' => 'Tungawan',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            3 => 
            array (
                'id' => 4,
                'campus' => 'Naga',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            4 => 
            array (
                'id' => 5,
                'campus' => 'Ipil',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            5 => 
            array (
                'id' => 6,
                'campus' => 'Alicia',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            6 => 
            array (
                'id' => 7,
                'campus' => 'Mabuhay',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            7 => 
            array (
                'id' => 8,
                'campus' => 'Olutanga',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            8 => 
            array (
                'id' => 9,
                'campus' => 'Siay',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            9 => 
            array (
                'id' => 10,
                'campus' => 'Malangas',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            10 => 
            array (
                'id' => 11,
                'campus' => 'Imelda',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            11 => 
            array (
                'id' => 12,
                'campus' => 'Diplahan',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            12 => 
            array (
                'id' => 13,
                'campus' => 'Aurora',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            13 => 
            array (
                'id' => 14,
                'campus' => 'Molave',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            14 => 
            array (
                'id' => 15,
                'campus' => 'Pagadian',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            15 => 
            array (
                'id' => 16,
                'campus' => 'Curuan',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 2,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:27:13',
                'updated_at' => '2024-10-07 11:27:13',
            ),
            16 => 
            array (
                'id' => 17,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 3,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:33:42',
                'updated_at' => '2024-10-07 11:33:42',
            ),
            17 => 
            array (
                'id' => 18,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 4,
                'agency_id' => 15,
                'created_at' => '2024-10-07 11:40:42',
                'updated_at' => '2024-10-07 11:40:42',
            ),
            18 => 
            array (
                'id' => 19,
                'campus' => 'Sindangan',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 4,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:40:42',
                'updated_at' => '2024-10-07 11:40:42',
            ),
            19 => 
            array (
                'id' => 20,
                'campus' => 'Buug',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 4,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:40:42',
                'updated_at' => '2024-10-07 11:40:42',
            ),
            20 => 
            array (
                'id' => 21,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 5,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:52:54',
                'updated_at' => '2024-10-07 11:52:54',
            ),
            21 => 
            array (
                'id' => 22,
                'campus' => 'Pagadian Annex',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 9,
                'school_id' => 5,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:52:54',
                'updated_at' => '2024-10-07 11:52:54',
            ),
            22 => 
            array (
                'id' => 23,
                'campus' => 'Dumingag',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 5,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:52:54',
                'updated_at' => '2024-10-07 11:52:54',
            ),
            23 => 
            array (
                'id' => 24,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 6,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:54:47',
                'updated_at' => '2024-10-07 11:54:47',
            ),
            24 => 
            array (
                'id' => 25,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 7,
                'agency_id' => 10,
                'created_at' => '2024-10-07 11:56:25',
                'updated_at' => '2024-10-07 11:56:25',
            ),
            25 => 
            array (
                'id' => 26,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 8,
                'agency_id' => 10,
                'created_at' => '2024-10-07 12:04:01',
                'updated_at' => '2024-10-07 12:04:01',
            ),
            26 => 
            array (
                'id' => 27,
                'campus' => 'Dipolog',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 8,
                'agency_id' => 10,
                'created_at' => '2024-10-07 12:04:01',
                'updated_at' => '2024-10-07 12:04:01',
            ),
            27 => 
            array (
                'id' => 28,
                'campus' => 'Tampilisan',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 8,
                'agency_id' => 10,
                'created_at' => '2024-10-07 12:04:01',
                'updated_at' => '2024-10-07 12:04:01',
            ),
            28 => 
            array (
                'id' => 29,
                'campus' => 'Katipunan',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 8,
                'agency_id' => 10,
                'created_at' => '2024-10-07 12:04:01',
                'updated_at' => '2024-10-07 12:04:01',
            ),
            29 => 
            array (
                'id' => 30,
                'campus' => 'Siocon',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 8,
                'agency_id' => 10,
                'created_at' => '2024-10-07 12:04:01',
                'updated_at' => '2024-10-07 12:04:01',
            ),
            30 => 
            array (
                'id' => 31,
                'campus' => 'Sibuco',
                'is_main' => 0,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 8,
                'agency_id' => 10,
                'created_at' => '2024-10-07 12:04:01',
                'updated_at' => '2024-10-07 12:04:01',
            ),
            31 => 
            array (
                'id' => 32,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 9,
                'agency_id' => 10,
                'created_at' => '2024-10-09 13:39:15',
                'updated_at' => '2024-10-09 13:39:15',
            ),
            32 => 
            array (
                'id' => 33,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 10,
                'agency_id' => 10,
                'created_at' => '2024-10-09 13:42:10',
                'updated_at' => '2024-10-09 13:42:10',
            ),
            33 => 
            array (
                'id' => 34,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 10,
                'school_id' => 11,
                'agency_id' => 10,
                'created_at' => '2024-10-09 13:46:19',
                'updated_at' => '2024-10-09 13:46:19',
            ),
            34 => 
            array (
                'id' => 35,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 9,
                'school_id' => 12,
                'agency_id' => 10,
                'created_at' => '2024-10-09 13:49:48',
                'updated_at' => '2024-10-09 13:49:48',
            ),
            35 => 
            array (
                'id' => 36,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 9,
                'school_id' => 13,
                'agency_id' => 10,
                'created_at' => '2024-10-09 13:53:59',
                'updated_at' => '2024-10-09 13:53:59',
            ),
            36 => 
            array (
                'id' => 37,
                'campus' => 'Main',
                'is_main' => 1,
                'is_alone' => 0,
                'is_active' => 1,
                'term_id' => 5,
                'grading_id' => 9,
                'school_id' => 14,
                'agency_id' => 10,
                'created_at' => '2024-10-09 13:57:04',
                'updated_at' => '2024-10-09 13:57:04',
            ),
        ));

        
    }
}